### ISSUE TITLE
npm: '5.5.1' . 

### ISSUE THREAD

**Issue by lancelot9527** [hua1995116/webchat#12]
npm install 报错 
`npm ERR! Cannot read property '0' of undefined。`
npm run dev 报错

> vuepro@1.0.0 dev /Users/lanpan/Downloads/webchat-master
> node build/dev-server.js NODE_ENV=development

> Starting dev server...
(node:851) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
`
`
events.js:182
      throw er; // Unhandled 'error' event
      ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/lanpan/Downloads/webchat-master/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:115:13)
    at Pool.emit (events.js:210:7)
    at Connection.<anonymous> (/Users/lanpan/Downloads/webchat-master/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at Connection.emit (events.js:213:7)
    at Socket.<anonymous> (/Users/lanpan/Downloads/webchat-master/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at NativeConnection.<anonymous> (/Users/lanpan/Downloads/webchat-master/node_modules/mongoose/lib/connection.js:317:17)
    at NativeConnection.deprecated [as open] (internal/util.js:52:15)
    at Mongoose.connect (/Users/lanpan/Downloads/webchat-master/node_modules/mongoose/lib/index.js:268:47)
    at Object.<anonymous> (/Users/lanpan/Downloads/webchat-master/build/dev-server.js:34:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuepro@1.0.0 dev: `node build/dev-server.js NODE_ENV=development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vuepro@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by lancelot9527** [comment]
也没找到Index.vue，找到Chat.vue但文件里没有io.connect

**Comment by hua1995116** [comment]
 @lancelot9527 你好，是这样的。
1.一开始的报错是因为你没有装mongodb数据库吧。请检查你的数据库是否连接成功。
2.因为之前版本迭代没有及时更新md文件，在老版下配置是那样的，现在重构后的项目请看，[https://github.com/hua1995116/webchat/blob/master/README.md](https://github.com/hua1995116/webchat/blob/master/README.md )

**Comment by lancelot9527** [comment]
mongodb 安装了。安装后直接运行就可以了吗？  然后再npm run dev运行您的demo？

**Comment by hua1995116** [comment]
@lancelot9527 截图你的错误。
