### ISSUE TITLE
你好，我想请问下，我在npm run dev 的时候就报错了，是为什么呢，然后貌似那个数据库我连接的问题，请问这个要如何解决

### ISSUE THREAD

**Issue by Alansherlock** [hua1995116/webchat#2]
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

**Comment by hua1995116** [comment]
请看这个。https://stackoverflow.com/questions/41611146/mongoerror-failed-to-connect-to-server-localhost27017-on-first-connect

**Comment by zsychy** [comment]
@Alansherlock 老铁你那个问题解决了么

**Comment by fengdafeng** [comment]
刚开始学，下载下来打开报这些错，求大神指点
> vuepro@1.0.0 dev D:\githubClone\webchat
> node build/dev-server.js NODE_ENV=development

module.js:491
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\githubClone\webchat\build\check-versions.js:1:75)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuepro@1.0.0 dev: `node build/dev-server.js NODE_ENV=development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vuepro@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASUS\AppData\Roaming\npm-cache\_logs\2018-01-23T13_29_42_330Z-debug.log
